services:
  techdeskpro:
    image: php:8.3-apache
    container_name: techdeskpro
    restart: unless-stopped
    volumes:
      - ./public_html:/var/www/html
      - ./private:/var/www/private
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    networks:
      - homelab-proxy
      - homelab-backend

networks:
  homelab-proxy:
    external: true
  homelab-backend:
    external: true
