services:
  techdeskpro:
    build: .
    container_name: techdeskpro
    restart: unless-stopped
    networks:
      - homelab-proxy
      - homelab-backend

networks:
  homelab-proxy:
    external: true
  homelab-backend:
    external: true
